# адрес запуска сервера
HOST = "0.0.0.0"
# порт запуска сервера
PORT = "8080"
# строка подключения к БД
DATABASE_URL = "host=db user=postgres password=1 port=5432 dbname=logs sslmode=disable connect_timeout=15000"
# Максимальное количество сессий БД
MAX_DB_SESSIONS = 50
# Время жизни незадействованного соединения к БД в секундах
MAX_DB_SESSION_IDLE_TIME = 10
# Максимальное количество записей лога, возвращающемое по запросу
MAX_LOG_RECORDS_RESULT = 1000
# Таймаут на чтение для HTTP сервера в миллисекундах
# Время на чтение заголовков и тела входящего запроса
HTTP_READ_TIMEOUT = 1000
# Таймаут на запись для HTTP сервера в миллисекундах
# Время после окончания чтения заголовков и тела входящего запроса и до окончания ответа
HTTP_WRITE_TIMEOUT = 10000
# Таймаут на чтение из БД в миллисекундах
# Должен быть меньше чем HTTP_WRITE_TIMEOUT
DB_READ_TIMEOUT = 8000
# Таймаут на запись в БД в миллисекундах
# Не связан с таймаутами http, т.к. запись в БД идет асинхронно
DB_WRITE_TIMEOUT = 5000
# Таймаут завершения HTTP сервера в секундах
HTTP_SHUTDOWN_TIMEOUT = 10
# Максимальное количество запросов в секунду
RATE_LIMIT = 5000
# Пиковое максимальное количество запросов в секунду
RATE_LIMIT_BURST = 10000
# Токены доступа. Передаются клиентами для проверки прав
TOKENS = [
    "dbda0fba4da680c615340d6faa2868eb5413c3b837640078b87149872257f842",
    "b408b10c9c53830dff0eae8f59b034ef71333d7f43e429f6dba212ff65d7044e",    
]
